language: python
os: linux
python: 3.7

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $HEROKU_APP_NAME .
        - docker images
        - docker tag covid-bot-ec $DOCKER_USERNAME/$HEROKU_APP_NAME
        - docker push $DOCKER_USERNAME/$HEROKU_APP_NAME
#deploy:
#  provider: heroku
#  api_key: $HEROKU_KEY
#  app: $HEROKU_APP_NAME
#  run:
#    - "python kbsbot/cvtelegramchannel/launch.py"

